name: "Run Container Scan on Super Mario Docker Image with Quality Gate"
 
on:
  push:
    branches:
      - main
 
env:
  # Using simple shell arithmetic for version increment
  VERSION: $(( $(cat version.txt) + 1 ))
 
jobs:
  
  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        
      - name: Get Docker Image from Docker Hub
        run: |
          docker pull docker.io/fairyinabottle4/supermariogitopsproject:${{ env.VERSION }}
          # File saved to the workspace root: /github/workspace/supermariolatestdockerimage.tar
          docker save -o supermariolatestdockerimage.tar docker.io/fairyinabottle4/supermariogitopsproject:${{ env.VERSION }}
      
      - name: Run Trivy vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@master
        with:
          # Using the relative path (just the filename)
          input: supermariolatestdockerimage.tar
          exit-code: '0'
          severity: 'CRITICAL,HIGH'